---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  # - name: centos-7

suites:
  - name: smoke-install
    run_list:
      - recipe[kubernetes-stack-test::default]
      - recipe[kubernetes-stack-test::install]
    verifier:
      inspec_tests:
        - test/smoke/default/default_test.rb
        - test/smoke/kubectl/kubectl_install_test.rb
        - test/smoke/gcloud/gcloud_install_test.rb
        - test/smoke/helm/helm_install_test.rb
        - test/smoke/minikube/minikube_install_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true,
          version: ""
        gcloud:
          enabled: true,
          version: ""
        helm:
          enabled: true,
          version: ""
        minikube:
          enabled: true,
          version: "v0.25.2"
          k8s_version: ""
          network_plugin: "cni"
          bootstrapper: "kubeadm"
          vm_driver: "none"

  - name: smoke-uninstall
    run_list:
      - recipe[kubernetes-stack-test::default]
      - recipe[kubernetes-stack-test::uninstall]
    verifier:
      inspec_tests:
        - test/smoke/default/default_test.rb
        - test/smoke/gcloud/gcloud_uninstall_test.rb
        - test/smoke/helm/helm_uninstall_test.rb
        - test/smoke/kubectl/kubectl_uninstall_test.rb
        - test/smoke/minikube/minikube_uninstall_test.rb
    attributes:
      kubernetes-stack:
        kubectl:
          enabled: true,
          version: ""
        gcloud:
          enabled: true,
          version: ""
        helm:
          enabled: true,
          version: ""
        minikube:
          enabled: true,
          version: "v0.25.2"
          k8s_version: ""
          network_plugin: "cni"
          bootstrapper: "kubeadm"
          vm_driver: "none"
